export const ROUTES = {
  HOME:                 "/",
  LOGIN:                "/login",
  REGISTER:             "/register",
  DASHBOARD:            "/dashboard",
  LEARNING_PATHS:       "/paths",
  LEARNING_PATH_DETAIL: "/paths/:id",
  CLASSROOM:            "/classrooms",
  CLASSROOM_DETAIL:     "/classrooms/:id",
  ANALYTICS:            "/analytics",
  COMMUNITY:            "/community",
  COMMUNITY_DETAIL:     "/community/:id",
  PROFILE:              "/profile",
  SETTINGS:             "/settings",
  CERTIFICATES:         "/certificates",
  ADMIN:                "/admin",
  NOT_FOUND:            "*",
} as const;
